steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sandbox-tomvdb/tensorflow-mnist-flask:$SHORT_SHA', '.']
images: ['gcr.io/sandbox-tomvdb/tensorflow-mnist-flask:$SHORT_SHA']